### ISSUE TITLE
Undefined behaivour in dependency extism 0.4.0 : `extism::Plugin.call_map`

### ISSUE THREAD

**Issue by mtb0x1** [dylibso/modsurfer#64] opened 2023-10-30 14:06 UTC
I am using the last version available on github.

**Command to reproduce :** 
`cargo run -- generate -p ~/apps/rust/llama2.rs.wasm/www/pkg/llama2_rs_wasm_bg.wasm -o /tmp/mod.yml`
the wasm file is available [here](https://github.com/mtb0x1/llama2.rs.wasm/releases/download/latest/www.tar.gz)

**Result :** 
`���MzU;-A���enabled for shared memories (at offset 0x80d)`

**Expected Result :**  
`threads must be enabled for shared memories (at offset 0x80d)`

My first guess was related to non UTF-8 characters, I checked the Error String and its UTF-8 compliant.
Most certain this related to lifetime and FFI bounds on 'Plugin::Internal' and 'Plugin::Internal::last_error'.
A chain of calls pass around a reference of a owned string and eventually display it to the user, except the owner of that string (Internal) gets freed before. 

My naive fix would be to allocate a string for the error as soon we have it, it doesn't cost that much and it should have an impact only on non-happy paths (Errors).
In `extism 0.4.0`
```diff

diff --git a/src/plugin.rs b/src/plugin.rs
index 150ce69..3289e49 100644
--- a/src/plugin.rs
+++ b/src/plugin.rs
@@ -255,7 +255,7 @@ impl<'a> Plugin<'a> {
             let err = unsafe { bindings::extism_error(context, self.id) };
             if !err.is_null() {
                 let s = unsafe { std::ffi::CStr::from_ptr(err) };
-                return Err(Error::msg(s.to_str().unwrap()));
+                return Err(Error::msg(s.to_str().unwrap().to_string()));
             }

             return Err(Error::msg("extism_call failed"));
```
N.B : I tried to upgrade extism to the last version but it seems that there is a lot of differences. (I imagine it's a WIP)

**Comment by nilslice** [comment] 2023-10-30 14:10
thank you! I will update Extism, as there have been a bunch of memory-related improvements since this feature was added in Modsurfer. 

I think I can get around to it in the next day or so, and will ping you on this issue when it's done. Would appreciate if you could help test!

**Comment by wikiwong** [comment] 2023-10-30 20:11
I tested upgrading Extism to `0.5.4` and it seems to have fixed the error message display for me.  @mtb0x1 can you please test out this branch when you get a chance? https://github.com/dylibso/modsurfer/pull/65

I introduced a segfault in my test to make sure that was displaying correctly, but would be good to ensure the error message you received around threads looks good too

**Comment by nilslice** [comment] 2023-10-30 20:14
(unrelated, but thank you @mtb0x1 for your PR on dylibso/hermit as well!)

**Comment by wikiwong** [comment] 2023-10-30 20:17
@mtb0x1 just noticed you did provide the llama2_rs_wasm_bg.wasm file.  I tested it out and got a segfault instead of the error regarding threads:
```
[1]    51115 segmentation fault (core dumped)  cargo run -- generate -p ~/Downloads/www/pkg/llama2_rs_wasm_bg.wasm 
```

so looks like something else is at play here, will continue to look

**Comment by mtb0x1** [comment] 2023-10-30 21:28
> so looks like something else is at play here, will continue to look
I think its a different result for the same issue, I think it's still the undefined behavior that leads to seg. fault now and before it was only liberating the memory allocated for the error message.

I still believe that doing this in plugin.rs#L257 solves this issue.( to_string() : makes an allocation and thus new data != from the one returned by `extism_error`)
```diff
-                return Err(Error::msg(s.to_str().unwrap()));
+                return Err(Error::msg(s.to_str().unwrap().to_string()));
```

another way would be to use lifetime and make sure that data pointed by the pointer returned by `extism_error` lives long enough.

**Comment by wikiwong** [comment] 2023-10-30 21:39
Re-opening - it closed automatically when I merged the PR that was linked to this

**Comment by wikiwong** [comment] 2023-10-30 21:43
@mtb0x1 The actual error you were seeing related to threads should be fixed with: https://github.com/dylibso/modsurfer/pull/66.  I verified with your module, but please feel free to test on main as well. 
 We'll cut a release for it shortly.

I'll leave this issue open as it refers to the actual error message coming from the Extism plugin not being displayed correctly

**Comment by mtb0x1** [comment] 2023-10-30 21:54
> The actual error you were seeing related to threads should be fixed with: #6**6**. I verified with your module, but please feel free to test on main as well. We'll cut a release for it shortly.

I confirm #66 let me generate the mod file now. (since it introduces the support wasm using threads).

**Comment by nilslice** [comment] 2023-10-30 21:56
I also think that what @mtb0x1 suggests with this patch is correct: 

```patch
-                return Err(Error::msg(s.to_str().unwrap()));
+                return Err(Error::msg(s.to_str().unwrap().to_string()));
```

And it should be resolved in the latest version of Extism. However we'd have to throw some error in a plugin somewhere to test it precisely. 

IMO, we can close this now that #66 is confirmed. We'll work out some tests to check this in extism upstream, as we're heading to release v1.0 later this year / beginning of 2024.

**Closed by nilslice** 2023-10-30 21:56 UTC

**Comment by wikiwong** [comment] 2023-10-30 22:26
Captured the issue here: https://github.com/extism/extism/issues/555

Thanks again @mtb0x1 !
